<a href="https://colab.research.google.com/github/Ekta-Shah/python_practice/blob/main/numpy_exercises_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [3]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
array1 = np.array([1,2,3,4,5])

# Create a 2-dimensional NumPy array using np.array()

array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
# Create a 3-dimensional Numpy array using np.array()
array3 = np.array([[[1.1,1.2,1.3],[2.1,2.2,2.3],[3.1,3.2,3.3]],[[4.1,4.2,4.3],[5.1,5.2,5.3],[6.1,6.2,6.3]],[[7.1,7.2,7.3],[8.1,8.2,8.3],[9.1,9.2,9.3]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
print(f"dim:{array1.ndim}, shape :{array1.shape}, data type: {array1.dtype}, size: {array1.size}, type: {type(array1)}")

dim:1, shape :(5,), data type: int64, size: 5, type: <class 'numpy.ndarray'>


In [6]:
# Attributes of 2-dimensional array
print(f"dim:{array2.ndim}, shape :{array2.shape}, data type: {array2.dtype}, size: {array2.size}, type: {type(array2)}")

dim:2, shape :(3, 3), data type: int64, size: 9, type: <class 'numpy.ndarray'>


In [7]:
# Attributes of 3-dimensional array
print(f"dim:{array3.ndim}, shape :{array3.shape}, data type: {array3.dtype}, size: {array3.size}, type: {type(array3)}")

dim:3, shape :(3, 3, 3), data type: float64, size: 27, type: <class 'numpy.ndarray'>


In [8]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(array2)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [9]:
# Create an array of shape (10, 2) with only ones
arr10_2 = np.zeros((10,2), dtype=int)
arr10_2

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [10]:
# Create an array of shape (7, 2, 3) of only zeros
arr7_2_3 = np.zeros((7,2,3), dtype=int)
arr7_2_3

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [11]:
# Create an array within a range of 0 and 100 with step 3
arr = np.arange(0,100,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [12]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr = np.random.randint(0,10,(7,2))
arr

array([[2, 1],
       [8, 5],
       [8, 6],
       [0, 0],
       [6, 9],
       [7, 4],
       [4, 3]])

In [13]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr = np.random.rand(3,5)
arr

array([[0.43988733, 0.10556591, 0.36562407, 0.09837815, 0.74602895],
       [0.96520968, 0.77960916, 0.68432958, 0.1141759 , 0.84103829],
       [0.52191228, 0.60266033, 0.49516455, 0.80779418, 0.56359019]])

In [14]:
# Set the random seed to 42

gen  = np.random.default_rng(seed=42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
arr = gen.integers(0,10,(4,6))
arr

array([[0, 7, 6, 4, 4, 8],
       [0, 6, 2, 0, 5, 9],
       [7, 7, 7, 7, 5, 1],
       [8, 4, 5, 3, 1, 9]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [19]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr = gen.integers(1,10,(3,7))

# Find the unique numbers in the array you just created
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
# Find the 0'th index of the latest array you created
arr[0]

array([5, 7, 3, 8, 6, 5, 5])

In [21]:
# Get the first 2 rows of latest array you created
arr[:2]

array([[5, 7, 3, 8, 6, 5, 5],
       [6, 1, 2, 3, 2, 4, 7]])

In [22]:
# Get the first 2 values of the first 2 rows of the latest array
arr[:2,:2]

array([[5, 7],
       [6, 1]])

In [23]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr1 = np.random.randint(0,10,(3,5))
arr2 = np.ones((3,5))

In [25]:
# Add the two arrays together
arr3=arr1+arr2

In [26]:
# Create another array of ones of shape (5, 3)
arr4 = np.ones((5,3))

In [27]:
# Try add the array of ones and the other most recent array together
arr3+arr4

ValueError: ignored

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [28]:
# Create another array of ones of shape (3, 5)
arr5 = np.ones((3,5))

In [31]:
# Subtract the new array of ones from the other most recent array
arr6 = arr3-arr5

In [34]:
# Multiply the ones array with the latest array
arr7 = arr6*arr5

In [36]:
# Take the latest array to the power of 2 using '**'
arr8 = arr7**2

In [37]:
# Do the same thing with np.square()
np.square(arr7)

array([[ 0., 16.,  1.,  9., 49.],
       [81.,  9., 36., 36.,  1.],
       [ 1., 64.,  9., 36., 36.]])

In [40]:
# Find the mean of the latest array using np.mean()
arr8.mean()

25.6

In [39]:
# Find the maximum of the latest array using np.max()
arr8.max()

81.0

In [41]:
# Find the minimum of the latest array using np.min()
arr8.min()

0.0

In [42]:
# Find the standard deviation of the latest array
arr8.std()

24.377038376308143

In [43]:
# Find the variance of the latest array
arr8.var()

594.2399999999999

In [46]:
# Reshape the latest array to (3, 5, 1)
arr8=arr8.reshape((3,5,1))

In [50]:
# Transpose the latest array
arr8=arr8.T

What does the transpose do?

In [51]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr9 = np.random.randint(0,10,(3,3))
arr10 = np.random.randint(0,10,(3,2))

In [54]:
# Perform a dot product on the two newest arrays you created
arr9.dot(arr10)

array([[ 32,  48],
       [ 82, 122],
       [ 51,  95]])

In [55]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr11 = np.random.randint(0,10,(4,3))
arr12 = np.random.randint(0,10,(4,3))

In [56]:
# Perform a dot product on the two newest arrays you created
np.dot(arr11,arr12)

ValueError: ignored

It doesn't work. How would you fix it?

In [57]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(arr11,arr12.T)

array([[ 49,  79,  86,  15],
       [ 66, 120,  99,  21],
       [ 40,  46,  72,  15],
       [ 76, 124, 117,  26]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [58]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr13 = np.random.randint(0,10,(5,6))
arr14 = np.random.randint(0,10,(5,6))

In [59]:
# Compare the two arrays with '>'
arr13>arr14

array([[False,  True, False,  True, False, False],
       [ True, False, False,  True, False,  True],
       [False, False, False,  True,  True, False],
       [False,  True,  True,  True, False, False],
       [ True, False, False, False, False,  True]])

What happens when you compare the arrays with `>`?

In [60]:
# Compare the two arrays with '>='
arr13>=arr14

array([[False,  True, False,  True, False, False],
       [ True, False,  True,  True,  True,  True],
       [False, False, False,  True,  True, False],
       [False,  True,  True,  True,  True,  True],
       [ True, False, False, False, False,  True]])

In [61]:
# Find which elements of the first array are greater than 7
arr13>7

array([[ True,  True, False, False, False, False],
       [False, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False],
       [False, False, False, False, False, False]])

In [62]:
# Which parts of each array are equal? (try using '==')
arr13==arr14

array([[False, False, False, False, False, False],
       [False, False,  True, False,  True, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [False, False, False, False, False, False]])

In [64]:
# Sort one of the arrays you just created in ascending order
arr13.sort()
arr13

array([[1, 2, 6, 7, 8, 8],
       [0, 2, 4, 4, 7, 9],
       [0, 0, 1, 1, 5, 6],
       [3, 4, 6, 6, 7, 9],
       [1, 3, 3, 5, 5, 7]])

In [67]:
arr14

array([[9, 6, 9, 2, 9, 8],
       [1, 4, 2, 3, 7, 4],
       [6, 9, 5, 2, 0, 2],
       [9, 1, 5, 1, 9, 6],
       [0, 8, 3, 4, 6, 4]])

In [66]:
# Sort the indexes of one of the arrays you just created
arr14.argsort()

array([[3, 1, 5, 0, 2, 4],
       [0, 2, 3, 1, 5, 4],
       [4, 3, 5, 2, 0, 1],
       [1, 3, 2, 5, 0, 4],
       [0, 2, 3, 5, 4, 1]])

In [68]:
# Find the index with the maximum value in one of the arrays you've created
arr14.argmax()

0

In [71]:
# Find the index with the minimum value in one of the arrays you've created
arr14.argmin()

16

In [72]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
arr14.argmax(axis=1)

array([0, 4, 1, 0, 1])

In [73]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
arr14.argmin(axis=0)

array([4, 3, 1, 3, 2, 2])

In [75]:
# Create an array of normally distributed random numbers
np.random.randn(5)

array([ 1.87193447, -0.00791168,  1.0698769 ,  0.24689709,  0.94432108])

In [79]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.